function fieldSet = blankSet(n)
fieldSet.Ex = zeros(1,n);
fieldSet.Ey = zeros(1,n);
fieldSet.Ez = zeros(1,n);
fieldSet.noisex = zeros(1,n);
fieldSet.noisey = zeros(1,n);
fieldSet.noisez = zeros(1,n);
fieldSet.E2x = zeros(1,n);
fieldSet.E2y = zeros(1,n);
fieldSet.E2z = zeros(1,n); 
fieldSet.coolingx = zeros(1,n);
fieldSet.coolingy = zeros(1,n);
fieldSet.coolingz = zeros(1,n);
fieldSet.slapx = zeros(1,n);
fieldSet.slapy = zeros(1,n);
fieldSet.slapz = zeros(1,n);
fieldSet.tweezer = zeros(1,n);